### ISSUE TITLE
Grammar/Syntax Checks for "Another Way to Think About Classes"

### ISSUE THREAD

**Issue by ACA1002** [scott-wilson/propersquid.com.old#4]
To make this clear up front, I am no scholar or authority on grammar and syntax. So take all comments or criticisms with a grain of salt. Additionally, these aren't critically important, and in fact may not cause any issues with reading comprehension for most people.

In paragraph 3:
"Classes and objects are really two things. Data and functions that work with that data."
The above is confusing because the second statement is completely disjointed from the first. A possible correction:
"Classes and objects are really two things: data, and functions that work with that data."

In paragraph 6:
"I have some functions that are usually referred to as getters that takes the whole object, and returns a part of it."
The above is grammatically incorrect due to plural form of the word "function." A possible correction:
"I have some functions that are usually referred to as getters that take the whole object, and return a part of it."

Lastly, you have a minor inconsistency with how you refer to your examples. 

In paragraph 4:
"Here’s a really basic example:"
While in later paragraphs followed by an example, you close the statement with just a period. This isn't _necessarily_ wrong, but at the end you explicitly state "Here’s an example." Consistent punctuation is a bit more satisfying, whether you choose to use normal periods, or normal colons to close statements preceding examples.

These are the only real "issues" I found, nothing else stands out.

Hope this helps.

**Comment by scott-wilson** [comment]
Wow, it's been a really long time since I've addressed this. First of all, thanks for the notes. Secondly, I'm currently in the process of rebuilding my website, so expect this fix in the new version that should be up... soonish?
